DROP TABLE IF EXISTS feedback;

CREATE TABLE feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source TEXT NOT NULL,
  region TEXT NOT NULL DEFAULT 'AMER',
  raw_text TEXT NOT NULL,
  sentiment TEXT NOT NULL,
  theme TEXT NOT NULL,
  summary TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'en',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
